name: Sync Figma variables to tokens (and code)
on:
  workflow_dispatch:
    inputs:
      project_key:
        description: 'The project key of the Figma project to generate tokens from'
        required: true

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Clear tokens directory
        run: bash scripts/cleanup.sh

      - name: Sync variables in Figma file to tokens
        run: npm run sync-figma-to-tokens -- --output tokens
        env:
          PROJECT_KEY: ${{ github.event.inputs.project_key }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.FIGMA_PAT }}

      - name: Remove dollar signs from output (SD won't work otherwise)
        run: bash scripts/removedollarsigns.sh
  
      - name: Build Style Dictionary (uses config.json to define src/dest)
        run: npm run build
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update tokens from Figma
          title: Update tokens from Figma
          # If necessary replace the id after "/files/" with your own organisation key
          body: 'Update tokens from Figma project: https://www.figma.com/files/945659260642889536/project/${{ github.event.inputs.project_key }}'
          branch: update-tokens
